import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import { io } from "socket.io-client";
import Chat from "../components/Chat";
import negotiate from "../utils/negotiate";

const socket = io();

export default function Home() {
  const [localStream, setLocalStream] = useState<MediaStream | null>(null);
  const [remoteStream, setRemoteStream] = useState<MediaStream | null>(null);
  const [screenStream, setScreenStream] = useState<MediaStream | null>(null);

  // initialize localStream, remoteStream & screenStream
  useEffect(() => {
    if (!remoteStream) {
      setRemoteStream(new MediaStream());
    }

    if (!localStream) {
      setLocalStream(new MediaStream());
    }

    if (!screenStream) {
      setScreenStream(new MediaStream());
    }
  }, []);

  // Peer Connection
  const [pc, setPc] = useState<RTCPeerConnection>();

  useEffect(() => {
    if (!pc) {
      setPc(
        new RTCPeerConnection({
          iceServers: [
            {
              urls: [
                "stun:stun1.l.google.com:19302",
                "stun:stun2.l.google.com:19302",
              ],
            },
          ],
        }),
      );
    }
  }, []);

  // Signalling Client
  useEffect(() => {
    if (pc) {
      socket.on("offer-event", async (offer) => {
        await pc.setRemoteDescription(new RTCSessionDescription(offer));

        if (offer.type === "offer") {
          console.log("receive offer => ", offer);
          const answer = await pc.createAnswer();
          await pc.setLocalDescription(answer);

          socket.emit("offer-event", answer);
          console.log("send answer => ", answer);
        }

        if (offer.type === "answer") {
          console.log("received answer => ", offer);
        }
      });

      socket.on("new-ice-candidate", (message) => {
        console.log("iceCAndiate =>", message);
        pc.addIceCandidate(new RTCIceCandidate(message));
      });
    }
  }, [pc]);

  // Attach listeners on the Peer connection
  useEffect(() => {
    if (!pc) return;

    pc.ontrack = (event) => {
      event.streams[0].getTracks().forEach((track) => {
        remoteStream?.addTrack(track);

        const videos = remoteStream?.getVideoTracks();
        if (videos?.length === 2) {
          screenStream?.addTrack(videos[1]);
        }
      });
    };

    pc.onicecandidate = (event) => {
      if (event.candidate) {
        socket.emit("new-ice-candidate", event.candidate.toJSON());
      }
    };

    pc.onnegotiationneeded = () => {
      negotiate(pc, socket);
    };
  }, [pc]);

  async function getCamera() {
    if (!pc) {
      return;
    }
    const videoStream = await navigator.mediaDevices.getUserMedia({
      video: true,
    });

    videoStream.getTracks().forEach((track) => {
      localStream?.addTrack(track);
      pc.addTrack(track, videoStream);
    });
  }

  async function getAudio() {
    const audioStream = await navigator.mediaDevices.getUserMedia({
      audio: true,
    });

    audioStream.getTracks().forEach((track) => {
      localStream?.addTrack(track); // maybe not necessary, as it'll be muted anyway
      pc?.addTrack(track, audioStream);
    });
  }

  async function connect() {
    if (!pc) {
      return;
    }

    negotiate(pc, socket);
  }

  async function shareScreen() {
    const screenCaptureStream = await navigator.mediaDevices.getDisplayMedia({
      video: true,
      audio: false,
    });

    screenCaptureStream.getTracks().forEach((track) => {
      screenStream?.addTrack(track);
      pc?.addTrack(track, screenCaptureStream);
    });
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen justify-between">
        <div>
          <video
            autoPlay
            className="-scale-x-100 bg-red-500"
            ref={(elem) => {
              if (elem) {
                elem.srcObject = localStream;
              }
            }}
            muted
          ></video>
          <video
            autoPlay
            className="-scale-x-100 bg-green-500"
            ref={(elem) => {
              if (elem) {
                elem.srcObject = remoteStream;
              }
            }}
          ></video>
          <video
            autoPlay
            className="bg-pink-500"
            ref={(elem) => {
              if (elem) {
                elem.srcObject = screenStream;
              }
            }}
          ></video>
          <button className="bg-cyan-500 px-4 py-2" onClick={getCamera}>
            Cam
          </button>
          <button className="bg-blue-500 px-4 py-2" onClick={getAudio}>
            Audio
          </button>
          <button className="bg-indigo-500 px-4 py-2" onClick={connect}>
            Connect
          </button>
          <button className="bg-pink-500 px-4 py-2" onClick={shareScreen}>
            Share Screen
          </button>
        </div>

        <Chat socket={socket} />
      </div>
    </div>
  );
}
